name: CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-apple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17.0
      - name: Install go stringer
        run: go get golang.org/x/tools/cmd/stringer@latest
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install libayatana-appindicator libpcsclite-dev
      - name: Build
        run: make build
