name: CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-apple:
    # The type of runner that the job will run on
    runs-on: macos-11
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.17.0

      - name: Install go stringer
        run: go get golang.org/x/tools/cmd/stringer@latest

      - name: build
        run: make build
